### ISSUE TITLE
unable to execute 

### ISSUE THREAD

**Issue by kimlabSchatterjee** [KurtzmanLab/SSTMap#114]
I am highly interested to use your tool for analyzing water orientation.  i installed it as per given instruction but during test it returns following error. Kindly help please 
make test_quick
cd tests/; python quick_test.py
Traceback (most recent call last):
  File "quick_test.py", line 3, in <module>
    from sstmap.grid_water_analysis import GridWaterAnalysis
ImportError: No module named sstmap.grid_water_analysis
Makefile:2: recipe for target 'test_quick' failed
make: *** [test_quick] Error 1

the tutorial page is not opening says page not found.
i have few queries kindly help

1. Sound I consider apo protein to run md simulation? If yes can you please guide me **what command or what mdp option should i use to restraint the protein. or make the protein rigid.**

2. as i understood  i need -i topol.top file -t trj.xtc -l lig.itp -g 34 45 46 -f 10000 -o output.txt files. am i correct (I want to use charrm ff)
3. how to **visualize** the data.How to determine/differentiate  thermodynamically stable and unstable waters? 
4. what files is should use to **plot** the data.
My questions may sounds like layman quarry. truly speaking i am from biology background. my supervisor  told me to dig in this experiments.  I know the basic methods to run gromacs and desmond md simulation. Please help

**Comment by kimlabSchatterjee** [comment]
after running it returns following error
**run_hsa -i topol.top -t ../md_100.xtc -l lig.pdb -f 1000 -s 0 -o hsa-out**
Initializing ...
Traceback (most recent call last):
  File "/home/kimlab/Downloads/amber20/miniconda/bin/run_hsa", line 33, in <module>
    sys.exit(load_entry_point('sstmap==1.1.4', 'console_scripts', 'run_hsa')())
  File "/home/kimlab/Downloads/amber20/miniconda/lib/python3.8/site-packages/sstmap-1.1.4-py3.8-linux-x86_64.egg/sstmap/scripts/run_hsa.py", line 94, in entry_point
    main()
  File "/home/kimlab/Downloads/amber20/miniconda/lib/python3.8/site-packages/sstmap-1.1.4-py3.8-linux-x86_64.egg/sstmap/scripts/run_hsa.py", line 81, in main
    h = SiteWaterAnalysis(top, traj,
  File "/home/kimlab/Downloads/amber20/miniconda/lib/python3.8/site-packages/sstmap-1.1.4-py3.8-linux-x86_64.egg/sstmap/utils.py", line 50, in function_timer
    result = function(*args, **kwargs)
  File "/home/kimlab/Downloads/amber20/miniconda/lib/python3.8/site-packages/sstmap-1.1.4-py3.8-linux-x86_64.egg/sstmap/site_water_analysis.py", line 103, in __init__
    super(SiteWaterAnalysis, self).__init__(topology_file, trajectory, supporting_file)
  File "/home/kimlab/Downloads/amber20/miniconda/lib/python3.8/site-packages/sstmap-1.1.4-py3.8-linux-x86_64.egg/sstmap/water_analysis.py", line 105, in __init__
    required_support = requirements[topology_extension][0]
KeyError: 'top'

**Comment by Yeonji-Ji** [comment]
Hello, Sorry that it took so long to answer.
1. Yes, you can prepare the protein before running MD simulation.
2. Yes, but please check the file formats SSTMap can read.
3. You can visualize it using VMD or pymol.
For the answers for 3 and 4, the link below might be helpful. 
[https://ambermd.org/tutorials/advanced/tutorial25/section1.htm]

_run_hsa -i topol.top -t ../md_100.xtc -l lig.pdb -f 1000 -s 0 -o hsa-out_
Did you try with "prmtop" or "parm7" format of the topology file instead of "top"?
