### ISSUE TITLE
Non existent file in command line input: Needs to fail better

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#28]
When a file that is specificied on the command line isn't found, the code needs to quit better and state that the file was not found.   This can be simply implemented by a simple check that all the files specified on the command line are present before anything is run.   Below is a case in which I put in a non-existent trajectory file "testcase.nc" and the output I got from it.   There should also be a check that all mandatory inputs are present...

amber simpleliquid$ run_hsa -i testcase.prmtop -t testcase.nc -l ligand.pdb -s -o "testcase"

Traceback (most recent call last):
  File "/Users/simpleliquid/anaconda2/bin/run_hsa", line 11, in <module>
    load_entry_point('sstmap==1.0', 'console_scripts', 'run_hsa')()
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/sstmap/scripts/run_hsa.py", line 49, in entry_point
    main()
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/sstmap/scripts/run_hsa.py", line 40, in main
    clustercenter_file=args.clusters, prefix=args.output_prefix)
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/sstmap/utils.py", line 54, in function_timer
    result = function(*args, **kwargs)
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/sstmap/site_water_analysis.py", line 97, in __init__
    start_frame, num_frames, supporting_file)
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/sstmap/water_analysis.py", line 90, in __init__
    first_frame = md.load_frame(self.trajectory, 0, top=self.topology_file)
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 307, in load_frame
    _assert_files_exist(filename)
  File "/Users/simpleliquid/anaconda2/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 99, in _assert_files_exist
    raise IOError('No such file: %s' % fn)
IOError: No such file: testcase.nc

**Comment by kamran-haider** [comment]
Yeah, should have done that before. Made the corresponding changes to the code. Thanks for catching.
