### ISSUE TITLE
Pip install

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#61]
Tried to install latest version with pip,  the program installed but the code didn't work. 

tkurtzman@micro1 SSTMAP_GIST]$ pip install git+git://github.com/kurtzmanlab/sstmap.git#egg=sstmap
Collecting sstmap from git+git://github.com/kurtzmanlab/sstmap.git#egg=sstmap
  Cloning git://github.com/kurtzmanlab/sstmap.git to /tmp/pip-build-wewgTb/sstmap
Installing collected packages: sstmap
  Running setup.py install for sstmap ... done
Successfully installed sstmap-1.0
[tkurtzman@micro1 SSTMAP_GIST]$ ls
aa2ar.prmtop  ligand.pdb  md10.in  md10.info  md10.nc  md10.out  md10.rst7  SSTMap_GIST10ns
[tkurtzman@micro1 SSTMAP_GIST]$ run_hsa
Traceback (most recent call last):
  File "/home/tkurtzman/anaconda2/bin/run_hsa", line 11, in <module>
    load_entry_point('sstmap==1.0', 'console_scripts', 'run_hsa')()
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/sstmap/__init__.py", line 41, in <module>
    from sstmap import site_water_analysis, grid_water_analysis, utils
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/sstmap/site_water_analysis.py", line 35, in <module>
    from memory_profiler import profile
ImportError: No module named memory_profiler
[tkurtzman@micro1 SSTMAP_GIST]$ run_gist
Traceback (most recent call last):
  File "/home/tkurtzman/anaconda2/bin/run_gist", line 11, in <module>
    load_entry_point('sstmap==1.0', 'console_scripts', 'run_gist')()
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/sstmap/__init__.py", line 41, in <module>
    from sstmap import site_water_analysis, grid_water_analysis, utils
  File "/home/tkurtzman/anaconda2/lib/python2.7/site-packages/sstmap/site_water_analysis.py", line 35, in <module>
    from memory_profiler import profile
ImportError: No module named memory_profiler

**Comment by kamran-haider** [comment]
Accidentally built dev version that's, fixed it by building the correct version.
